services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - TODOIST_API_KEY=${TODOIST_API_KEY}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  node_modules:
  db-data:
